### ISSUE TITLE
coinone/core.py 에서  :이 빠져 있습니다.

### ISSUE THREAD

**Issue by heartcored98** [gwangyi/pycoinone#1]
안녕하세요. 

이렇게 미리 짜주셔서 감사한 마음으로 쓰려는 학생입니다.

readme 파일에 있는데로 실행시켜봤는데 coinone/core.py 89번째 줄에 if 문 뒤에 콜론이 빠져 있는 것을 발견했습니다. 

```python
>>> from coinone.core import Coinone
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/pycoinone/coinone/core.py", line 89
    if time_to_sleep > 0
                       ^
SyntaxError: invalid syntax
>>> import coinone
>>> a = Coinone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Coinone' is not defined
>>> import coinone.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/pycoinone/coinone/core.py", line 89
    if time_to_sleep > 0
                       ^
SyntaxError: invalid syntax
```

**Comment by gwangyi** [comment]
아 이런 멍청한 실수를...ㅜㅜ 고쳤습니다.
